### ISSUE TITLE
ecoMax800 is not connected

### ISSUE THREAD

**Issue by Almaz90** [denpamusic/homeassistant-plum-ecomax#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Здравствуйте. Не удается подключить ecoMax 800R, он поддерживается данной интеграцией?
![0](https://github.com/user-attachments/assets/56d9af97-9e60-4b28-ab8e-093917a1bd68)
![1](https://github.com/user-attachments/assets/e5060d83-c905-4ccc-9d3e-b17f2d4eb567)
![2](https://github.com/user-attachments/assets/77e3fd97-99e4-432a-98d9-a6f538cd0044)

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

Sorry for delayed response, was offline for a couple days.

I checked diagnostics data, that we've collected from different devices and it seems that nobody tried the integration with EM800R device before, so I sadly cannot definitely confirm, that it is supported.

That being said, I've looked at manual for your device and I think it should work fine with this integration. It supports standard Plum modules like ecoLAMBDA and ecoSTER, which is good indicator that your device uses standard EM (ecoMAX) protocol as opposed to newer GM3 (GazModem 3), which we don't support yet.

From the error message, I can see that integration sees the connection, but fails to receive expected response from the EM.
This usually indicates hw problem, so first things to try would be following:
- swap D+ and D- wires around
- try different rs485 ports (if your device has multiple)
- try different USB to RS485 adapter, as `FTB6SPL3` serial from your first screenshot, indicates that your adapter is built using fake FTDI chip, which are prone to failures (see first comment [here](http://www.starlino.com/ftdi-chip-real-of-fake-how-to-spot-a-fake-rt232r-rt232rl-and-others.html))

**Comment by Taziff** [comment]
Can you write the software version of ecoMAX 800 module?

**Comment by Almaz90** [comment]
> Can you write the software version of ecoMAX 800 module?

panel v.01.20.22.B0
Module A: v.01.31.23.J1

**Comment by Almaz90** [comment]
> * swap D+ and D- wires around
> * try different rs485 ports (if your device has multiple)
> * try different USB to RS485 adapter, as `FTB6SPL3` serial from your first screenshot, indicates that your adapter is built using fake FTDI chip, which are prone to failures (see first comment [here](http://www.starlino.com/ftdi-chip-real-of-fake-how-to-spot-a-fake-rt232r-rt232rl-and-others.html))


D+ and D- changed, the problem remained. I tried connecting to both G1 and G2 - the result is the same. I'll try to order another adapter.

**Comment by Taziff** [comment]
> > Can you write the software version of ecoMAX 800 module?
> 
> panel v.01.20.22.B0 Module A: v.01.31.23.J1

Unfortunately, this is the last version of the program which does not support econet300.

**Comment by denpamusic** [comment]
@Almaz90
Taziff has been very helpful with EM-related information during development of this project, so I think we can trust his information on the issue. I keep this open, just in case you get it working, but if EM doesn't support ecoNET, there's not a lot we can do sadly. Sorry.

@Taziff
Thank you for the info!

**Comment by Taziff** [comment]
Module A program v01 is from 2013r. There is a newer program, but there is a high chance that the module will be damaged during the update.

**Comment by Almaz90** [comment]
> Taziff has been very helpful with EM-related information during development of this project, so I think we can trust his information on the issue. I keep this open, just in case you get it working, but if EM doesn't support ecoNET, there's not a lot we can do sadly. Sorry.


I ordered USR-TCP232-304. If it doesn't work out with him, then we'll close the issue.

**Comment by Almaz90** [comment]
Good afternoon. USR-TCP232-304 did not help, the problem remained. It looks like there really is a problem with the firmware

**Comment by denpamusic** [comment]
> Good afternoon. USR-TCP232-304 did not help, the problem remained. It looks like there really is a problem with the firmware

Hi,

Thank you very much for heads up, although I'm really sorry to hear that :(
I seems that I'll need to compile at least some sort of (un)supported device list...

**Comment by Taziff** [comment]
There is newer software for this device that supports econet300, but there is a high probability that something will go wrong during the update.

**Comment by Almaz90** [comment]
> There is newer software for this device that supports econet300, but there is a high probability that something will go wrong during the update.

Is it possible to revive the block later?

**Comment by ms-0-sm** [comment]
Hi same issue.
ecoMAX 800ec panel  v=17.10.01
Log:
ERROR (MainThread) [custom_components.plum_ecomax.config_flow] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/plum_ecomax/config_flow.py", line 188, in async_step_identify
    await self.identify_task
  File "/config/custom_components/plum_ecomax/config_flow.py", line 264, in _async_identify_device
    await self.connection.get(DeviceType.ECOMAX, timeout=DEFAULT_TIMEOUT),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyplumio/helpers/event_manager.py", line 66, in get
    await self.wait_for(name, timeout=timeout)
  File "/usr/local/lib/python3.13/site-packages/pyplumio/helpers/event_manager.py", line 52, in wait_for
    await asyncio.wait_for(self.create_event(name).wait(), timeout=timeout)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
