### ISSUE TITLE
Can start after update v0.3.8

### ISSUE THREAD

**Issue by speedypidz** [denpamusic/homeassistant-plum-ecomax#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hi Denis,

Hope you are well, after updating from v0.3.7 to v0.3.8, i'm experiencing problem to start the integration.

Thanks for your help

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
This error originated from a custom integration.

Logger: pyplumio.connection
Source: custom_components/plum_ecomax/connection.py:138
Integration: Plum ecoMAX (documentation, issues)
First occurred: 12:06:39 AM (13 occurrences)
Last logged: 12:11:17 AM

Can't connect to the device, retrying in 20.0 seconds

===============================================


Logger: homeassistant.bootstrap
Source: bootstrap.py:499
First occurred: 12:07:29 AM (5 occurrences)
Last logged: 12:11:29 AM

Waiting on integrations to complete setup: plum_ecomax

========================================

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/plum_ecomax/connection.py:138
Integration: Plum ecoMAX (documentation, issues)
First occurred: 12:11:35 AM (1 occurrences)
Last logged: 12:11:35 AM

Error setting up entry 192.168.20.50 for plum_ecomax
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 65, in _connect
    reader, writer = await self._open_connection()
  File "/usr/local/lib/python3.10/site-packages/pyplumio/helpers/timeout.py", line 17, in wrapper
    return await asyncio.wait_for(func(*args, **kwargs), timeout=seconds)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 141, in _open_connection
    return await asyncio.open_connection(
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.20.50', 8899)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 77, in _reconnect
    await self._connect()
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 72, in _connect
    raise ConnectionFailedError from connection_error
pyplumio.exceptions.ConnectionFailedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/plum_ecomax/__init__.py", line 91, in async_setup_entry
    await connection.async_setup()
  File "/config/custom_components/plum_ecomax/connection.py", line 138, in async_setup
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 97, in connect
    await self._reconnect()
  File "/usr/local/lib/python3.10/site-packages/pyplumio/connection.py", line 80, in _reconnect
    await self._connection_lost()
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi, thanks for the kind words and sorry for long wait.

Judging from the following log message, connection to the host 192.168.20.50 failed at OS level.
> OSError: [Errno 113] Connect call failed ('192.168.20.50', 8899)

Error 113 means that route to host was not found in the routing table. It probably has nothing to do with the version as it's failing on connection attempt, before PyPlumIO does anything at all with the connection.

Please try rebooting your Ethernet/WiFi to RS-485 converter, to force it to re-request IP from the router and try connecting to it again. To ensure that the converter is accessible, try running `ping 192.168.20.50` from the PC that runs HASS.

**Comment by speedypidz** [comment]
Hi Denis,I'm so sorry, because it's happen just when I updated the integration , I thought it was a bug. But you were right, don't know why my wifi module was not present on the network, after reboot everything is ok. Thank you so much .

Regards

**Comment by denpamusic** [comment]
You're welcome! And don't be sorry about opening an issue. Sometimes it's just more productive to contact the developer, instead of pulling you hair out, trying to figure out what went wrong😉

Anyway, glad that everything working now!

--
Best Wishes,
Denis
