### ISSUE TITLE
Problem ze znalezieniem urządzenia EM920P1-F

### ISSUE THREAD

**Issue by Marek7923** [denpamusic/homeassistant-plum-ecomax#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Witam serdecznie,  obecnie wyciągam dane dekodując je za pomocą modułu ecoNet300, ale do pełnego szczęścia chciał bym mieć możliwość zadawania parametrów/nastaw bezpośrednio z HA.
Podczas dodawania ręcznie integracji  i wybraniu połączenia przez TCP podaniu właściwego IP konwertera żadne urządzenie nie zostaje znalezione. 
Zmieniałem typy połączeń, oraz  prędkość transmisji danych od 9600 na 11520- próbuję nawiązać połącznie za pomocą modułu  USR-W610, niestety nie skutecznie.

Poprosił bym o podpowiedz co robię w niewłaściwy sposób. 

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [X] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [X] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
await fut
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/plum_ecomax/config_flow.py", line 189, in async_step_device
await self.device_task
File "/config/custom_components/plum_ecomax/config_flow.py", line 175, in _wait_for_device
self.device = await self.connection.get(ECOMAX, timeout=DEFAULT_TIMEOUT)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/event_manager.py", line 38, in get
await self.wait_for(name, timeout=timeout)
File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/event_manager.py", line 34, in wait_for
await asyncio.wait_for(self.create_event(name).wait(), timeout=timeout)
File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
raise exceptions.TimeoutError() from exc
TimeoutError
```

### My diagnostics data:

wersje oprogramowania układowego:
panel:             **16.20.19**
Moduł A:        **16.11.64 P1**
Moduł B:        **1.31.12**
ecoNET300:    **3.2.3819**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Marek7923** [comment]
Cześć,
- Udało się ;)
Ale po kolei,  kabelki sygnałowe podłączone prawidłowo  D+ = A
Przywróciłem konwerter do ustawień fabrycznych i sprawdziłem podesłane parametry transmisji, niestety też nie znajdowano urządzenia, 
wiec znów przeszedłem do zmiany prędkości w konwerterze i  zaczął pobierać dane z prędkością 115200 bitów.

**Bardzo dziękuję za pomoc, biorę się za testowanie ;)**

poniżej zamieszczę fotki z moimi działającymi nastawami, może komuś pomogą, 
na konie ostatnia fotka to moja wersja strony z HA z kotłownia ;)   
![ok 2023-12-03 180829](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/125127838/c052c41f-56d4-47e2-8635-f173e4d1d2c0)
![ok 2023-12-03 180809](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/125127838/7d6bf6ff-865e-4958-b21d-bfeeb4876fcc)
![kotłownia 2023-12-03 180457](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/125127838/bad613a3-ec6f-4265-a21b-3c891ba00b4a)
