### ISSUE TITLE
Cannot connect with ecoMAX360

### ISSUE THREAD

**Issue by jasienty** [denpamusic/homeassistant-plum-ecomax#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

I've got heat pump with ecoMAX360 (it is branded by HeatingPoland, Krommler) with ecoSTER touch pannel. I've connected EW11a RS-485-WIFI module parallel with touch screen but everytime I want to establish a connection in HA there is "no devices" prompt.
Not sure if I have correct configuration of EW11, but checked with every possible way and nothing helpes. Sometimes instead of "no devices found" prompt I get error connected with Flow control.
I've checked packets from EW11 in TCP/UDP debug tool and with those settings I can read S/N or model:
Baud Rate: 115200
Data Bit: 8
Stop Bit: 1
Parity: None
Buffer size: 512
Gap Time: 50
Protocol: Frame
Frame length: 14
Frame time: 100

Tried to change frame tags (Head and Tail) to 0x68 and 0x16 as described here: https://pyplumio.denpa.pro/protocol.html but it didn't help.

### I have following devices connected:

- [X] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.plum_ecomax.config_flow
Source: custom_components/plum_ecomax/config_flow.py:189
Integration: Plum ecoMAX (documentation, issues)
First occurred: 13:42:36 (5 occurrences)
Last logged: 13:45:43

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/plum_ecomax/config_flow.py", line 189, in async_step_device
    await self.device_task
  File "/config/custom_components/plum_ecomax/config_flow.py", line 175, in _wait_for_device
    self.device = await self.connection.get(ECOMAX, timeout=DEFAULT_TIMEOUT)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/event_manager.py", line 56, in get
    await self.wait_for(name, timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/pyplumio/helpers/event_manager.py", line 43, in wait_for
    await asyncio.wait_for(self.create_event(name).wait(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

I've not yet encountered any heat pumps controlled by an ecoMAX controller. All ecoMAX 3xx series that I've ecountered so far, has been wood or pellet boiler controllers. So sadly your device might simply use different protocol (e. g. GM3 same as ecoSOL) and is incompatible with this integration.

That being said you can try following settings for the **elfin EW11**. I've used this device myself for the long time, before switching to custom-made converter.

If that doesn't work also verify that you've connected A and B on the EW11 to the D+ and D- terminals on ecoMAX respectively.

## Communication Settings
![Screenshot 2024-01-10 at 16-54-39 EW11](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/c8c05e0e-7907-4da1-b012-2426d133e9bf)

## Serial Port Settings
![Screenshot 2024-01-10 at 16-54-06 EW11](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/d89a01ae-c7c3-4497-8f81-f0dcb089fff9)

**Comment by jasienty** [comment]
Hi!
I've tried with settings you provided but nothing changed ;( Also I double-checked wiring and it was correct.
So apparently my ecoMAX360i is not compatible with this integration. I will try to reconfigure it one more time and maybe I will find some error I've made.

Cheers!
Jan

**Comment by Taziff** [comment]
@jasienty w tej pompie ciepła jest sterownik ecoMulti który używa protokołu GazModem do komunikacji więc z tą integracją niestety jak na razie nie będzie działać.
@denpamusic can I write in Polish?

**Comment by jasienty** [comment]
@Taziff - niby tak, ale jednak jakieś dane wychwytuję z EW11, gdzie sterownik się przedstawia jako ecoMAX360i (jak robiłem update od producenta, to tak też były opisane pliki) i wyrzuca takie dane jak UID czy nazwy obiegów:
![Bez tytułu](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/50871593/344733fe-818c-4564-89c9-ba4c921e7559)
eng:
Taziff said that controller to my heat pump is ecoMulti, not ecoMAX360i - there is a different protocol used, thus I this integration won't work. On the screen attached I can see that I receive some information about my device - UID, ecoMAX360i and names of heating circuits.
Because I can get some information I am not sure if there is some problem with my EW11, transmission, protocol etc. or this controller has really different communication protocol.

**Comment by denpamusic** [comment]
> @denpamusic can I write in Polish?

Of course you can. Current translation software is quite good, so I've intentionally ommited English-only requirement in Code of conduct. Makes the place a bit friendlier and promotes feedback :)

Thanks for the help by the way. 👍

@jasienty
Judging from the frame size alone, it surely doesn't look like UIDResponse frame of the EM protocol, which normally should be around 30 bytes  in length. I think that @Taziff is right and your device uses GazModem3 (GM3) protocol which Plum's been using in it's heat pump devices, unless they've developed something entirely new ofc.

I've collected some info on the protocol here: https://github.com/denpamusic/homeassistant-plum-ecomax/issues/27#issuecomment-1773534034 and almost finished unit tests for it while on vacation. I plan on writing test version after I've done with options flow update for this integration. You can look in #27 for the progress update.

**Comment by jasienty** [comment]
ok, I won't argue then :)
I received this output with this settings on EW11, other settings gave only artefacts (maybe there was something in hex response, but didn't check):
![obraz](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/50871593/30d13fd4-5e21-47ce-b46a-223d28388422)
If you need any help with testing, let me know - I will do my best.

**Comment by janstolte** [comment]
@lachand -- I tried your custom component in my setup. Even though it connected correctly, it doesn't report any sensor values. This is what I'm getting:

<img width="333" height="382" alt="Image" src="https://github.com/user-attachments/assets/456d1bbb-6b2f-44aa-8d3b-5449abff5893" />

And basically, that is _all_ I'm getting. I am using a Waveshare ETH to RS485 device. It has a nice LED that tells me that it is seeing data. Checking the logs after installing the integration into HA, confirms this:

```
2025-12-17 17:34:41.741 INFO (MainThread) [custom_components.ecomax360.trame] 647800
2025-12-17 17:34:41.741 INFO (MainThread) [custom_components.ecomax360.trame] b'dx\x00'
```

I will go through your code to see if I can find something (e.g. a hardware address, communication settings, etc.) that might be adapted to my specific case. But if you have some suggestions to check, let me know.

**Comment by lachand** [comment]
Hello,
My integration was done via reverse engineering, and there are surely many things that must be specific to my configuration. For example, in parameters.py there is a SET_CODE variable that allows values to be sent to the controller. I don't remember how I got it, but I can look again.

I think the frame length can also be modified depending on the system, perhaps by trying without checking the lengths.
Finally, I used the sources and destinations that correspond to my system (ecomax + ecosther), so you would need to check that the addresses are the same for you.

There is a strong possibility that the indices of the following elements are specific to my installation:
    “MAIN_SOURCE”: {‘index’: 164, “type”: float},
    “RADIATOR_OUTLET”: {‘index’: 169, “type”: float},
    “DHW”: {‘index’: 179, “type”: float},
    “BUFFER_TANK”: {‘index’: 189, “type”: float},
    “OUTDOOR_TEMPERATURE”: {‘index’: 194, “type”: float}

As for the documentation, it wasn't really useful to me (I already had the short document), except for understanding the overall structure. I never managed to get a comprehensible list of parameters by using the documentation to help me build frames.

I can try to find the scripts I used for parsing, which helped me a lot.

Have a good evening.

**Comment by denpamusic** [comment]
@lachand @janstolte 
I'm really glad to see that there's work being done on the subject!
Just in case, here's full version of protocol documentation, maybe it'll be of some help to you.

[Standard transmission protocols ed.15.pdf](https://github.com/user-attachments/files/24476882/Standard.transmission.protocols.ed.15.pdf)

**Comment by janstolte** [comment]
I am not in a hurry, but very curious. As a matter of fact, I have been playing around with your software this afternoon, so your inputs are much appreciated.

One of my key finding was that command 0x02 is not listed as command in the documentation provided by @denpamusic . And in my case, the scanner you provided earlier did not yield any useful results in terms of values. So I created a script myself to catch some more data, but that is still work in progress.

Should you have something testable, let me know. But no rush.

**Comment by lachand** [comment]
I'm glad it seems to be working for you. It's surprising that the username and password changed. I'm using an ester_x40 thermostat and the credentials don't change. Please let me know the results of the read and write test when you've run it (test_full.py).

**Comment by lachand** [comment]
Yes, we can read the data correctly. The test I performed was on circuit 2 because it's the active circuit in my setup. However, we can read [113/118] Lecture tempcircuit2 ... ✅ 999.0, so maybe the second circuit is not the active circuit in your setup. You can usually find the active circuit via the touch panel. Otherwise, you can modify line 23 of test_full and replace circuit2, mixer2, etc. with circuit1, mixer1 to try, for example, circuit 1).

**Comment by jakobcichon** [comment]
Hi! :)
Great job, guys! I've got a Termet Heat Gold heat pump with an ecoMAX360i, and your work helped me a lot to start sniffing this protocol ;) In my setup, I connected a Raspberry Pi with an RS485 CAN HAT directly to the HMI device line. I'm able to capture data, and my goal is to read data from the controller and be able to change some settings. If you need to test data from my setup, just let me know ;)

**Comment by jasienty** [comment]
Hi Gents, I was away from Git for a while and I am more than happy that something has changed in this matter.
I want to actively help you in this matter - probably later this week I will try to test this integration in my env.
I can help with testing and translating to Polish. And if you have any tasks or things to test - please let me know!
Cheers!

**Comment by jasienty** [comment]
@lachand - Polish translation attached
[pl.json](https://github.com/user-attachments/files/25347307/pl.json)

**Comment by LeeNuss** [comment]
Hi everyone, great to see the progress on GM3 support here!
I've been working on a similar solution and wanted to share it in case anyone is interested to try it out or use it as reference. My approach uses a separate gateway service that handles the RS-485 serial communication, with a dedicated Home Assistant integration on top.

[econext-gateway](https://github.com/LeeNuss/econext-gateway) -- a service that runs on a device with a USB-to-RS485 adapter connected to the controller. It handles the GM3 protocol (discovery, bus token handling, polling) and exposes a REST API.
[ecoNEXT](https://github.com/LeeNuss/econext) -- a HACS integration for Home Assistant that connects to the gateway api and provides large number of sensors and controls. Currently supports parameter discovery (~1800 params), reading, writing, alarm history, and has climate entities for each active circuit.
Setup instructions are in the repository or here on this [forum thread](https://community.openenergymonitor.org/t/econext-direct-local-control-of-grant-hp290-econet-replacement-plum-ecomax360i/29758)
