### ISSUE TITLE
Cannot connect to ecoMAX850r2

### ISSUE THREAD

**Issue by jerz1985** [denpamusic/homeassistant-plum-ecomax#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hi,

I'm having issues with adding device in HA. I've connected EW11a RS-485-WIFI module to ecoSTER pins on the board.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
device.handle_frame(frame)
File "/usr/local/lib/python3.11/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
super().handle_frame(frame)
File "/usr/local/lib/python3.11/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
if frame.data is not None:
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/frames/__init__.py", line 159, in data
self.decode_message(self._message) if self._message is not None else {}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/frames/responses.py", line 222, in decode_message
return SchedulesStructure(self).decode(message)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/structures/schedules.py", line 188, in decode
start = message[offset + 1]
~~~~~~~^^^^^^^^^^^^
IndexError: index out of range
2024-01-17 15:09:30.316 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
device.handle_frame(frame)
File "/usr/local/lib/python3.11/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
super().handle_frame(frame)
File "/usr/local/lib/python3.11/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
if frame.data is not None:
^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/frames/__init__.py", line 159, in data
self.decode_message(self._message) if self._message is not None else {}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/frames/responses.py", line 222, in decode_message
return SchedulesStructure(self).decode(message)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyplumio/structures/schedules.py", line 188, in decode
start = message[offset + 1]
~~~~~~~^^^^^^^^^^^^
IndexError: index out of range
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

It seems like your boiler returns empty response to REQUEST_SCHEDULES[54], which leads to IndexError [here](https://github.com/denpamusic/PyPlumIO/blob/ba01c5dbcccd693ef4ec8813396afa4e4696ffce/pyplumio/structures/schedules.py#L188).

The easiest fix will be to check for empty response in the structure decoder.
